name: branch-dependent-step
on: [push, pull_request]
jobs:
    branch-dependent-step-job:
        runs-on: ubuntu-latest
        steps:
            - name: GITHUB_HEAD_REF
              if: github.event_name == 'pull_request'
              run: echo "${GITHUB_HEAD_REF}"
            - name: GITHUB_BASE_REF
              if: github.event_name == 'pull_request'
              run: echo "${GITHUB_BASE_REF}"
            - name: run only push
              if: github.event_name == 'push'
              run: echo "$GITHUB_REF_NAME"
            - name: (push) run target non master
              if: (github.event_name == 'push' && github.ref_name != 'master')
              run: echo "$GITHUB_EVENT_NAME"
            - name: (pull_request) run target non master
              if: (github.event_name == 'pull_request' && github.base_ref != 'master')
              run: echo "$GITHUB_EVENT_NAME"
            - name: run target non master
              if: (github.event_name == 'push' && github.ref_name != 'master') || (github.event_name == 'pull_request' && github.base_ref != 'master')
              run: echo "$GITHUB_EVENT_NAME"
