name: dynamic-matrix
on: [push, pull_request]

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - id: set-matrix
              run: echo "::set-output name=matrix::$(./generator.sh)"
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}

    run-matrix:
        needs: generate
        runs-on: ubuntu-latest
        strategy:
            matrix:
                package: ${{ fromJson(needs.generate.outputs.matrix) }}
        steps:
            - run: echo ${{ matrix.package }}
