name: macOSJob
on: [push, pull_request]
jobs:
    macos-echo:
        runs-on: macos-latest
        steps:
            - run: echo "I'm a pull request or push job."
            - run: env
            - run: echo -e "\033[1;31m This is red text \033[0m"
            - run: bash --version
