name: matrixEnv
on: [push, pull_request]

jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                config:
                    - {compiler : gcc, env : {ALCI_FOO : bar} }
        env:
            APCI_OS_NAME: $RUNNER_OS
        steps:
            - name: Hello World
              run: echo "Hello World on runner $APCI_OS_NAME"



