name: multi-step-job
on: [push, pull_request]
jobs:
    multi-step-job:
        runs-on: ubuntu-latest
        steps:
            - name: echo Variable
              run: echo "the value of FOO is -> ${FOO}"
              env:
                FOO: bar
            - name: checkout repo 
              uses: actions/checkout@v4
            - name: show folder
              run: |
                pwd
                ls
                echo ${GITHUB_WORKSPACE}
                ls ${GITHUB_WORKSPACE}
            - name: run script
              run: ./${GITHUB_WORKSPACE}/hello.sh
