name: variable-to-env-var
on: [push, pull_request]
jobs:
    ci:
        name: hwloc ${{ matrix.config.hwloc }}
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v7
            - name: set environment variable
              run: |
                ${{ matrix.config.hwloc == 'no' }} || echo "APCI_HWLOC=OFF" >> $GITHUB_ENV
            - name: display hwloc
              run: ${GITHUB_WORKSPACE}/display_hwloc.sh
        strategy:
            matrix:
                config:
                    - hwloc: yes
                    - hwloc: no
