name: variable-to-env-var
on: [push, pull_request]
jobs:
    ci:
        name: hwloc ${{ matrix.config.hwloc }}
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v7
            - name: set environment variable
              run: |
                ${{ matrix.config.hwloc == 'no' }} && echo "APCI_HWLOC=OFF" >> $GITHUB_ENV || true
            - name: display hwloc
              run: ${GITHUB_WORKSPACE}/display_hwloc.sh
            - name: set sysctl
              shell: bash
              run: |
                if [ "${{ matrix.config.hwloc}}" == 'yes' ]; then
                  sudo sysctl vm.mmap_rnd_bits=28
                fi
            - name: get systctl
              run: sudo sysctl -n vm.mmap_rnd_bits
        strategy:
            matrix:
                config:
                    - hwloc: yes
                    - hwloc: no
